version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: mtg_api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mtg
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

  db:
    image: postgres:15
    container_name: mtg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mtg
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  pgdata:
